from tkinter import *

def calc():
    result6.set(a3.get() * b3.get())
    result5.set( a3.get()*b2.get() + a2.get()*b3.get()) 
    result4.set( a2.get()*b2.get() + a3.get()*b1.get() + a1.get()*b3.get()) 
    result3.set( a2.get()*b1.get() + a1.get()*b2.get() + a3.get()*b0.get() + a0.get()*b3.get()) 
    result2.set( a1.get()*b1.get() + a2.get()*b0.get() + a0.get()*b2.get()) 
    result1.set( a1.get()*b0.get() + a0.get()*b1.get()) 
    result0.set( a0.get()*b0.get()) 
    
window = Tk()
a0 = DoubleVar()
a1 = DoubleVar()
a2 = DoubleVar()
a3 = DoubleVar()

b0 = DoubleVar()
b1 = DoubleVar()
b2 = DoubleVar()
b3 = DoubleVar()
result0 = DoubleVar()
result1 = DoubleVar()
result2 = DoubleVar()
result3 = DoubleVar()
result4 = DoubleVar()
result5 = DoubleVar()
result6 = DoubleVar()

Label(window, text = "三次多項式相乘", width = 12, bg = "lightgrey").grid(row = 0, column = 6)
Entry(window, width = 10, textvariable = a3).grid(row = 1, column = 3)
Label(window, width = 5, text = "x^3", bg = "lightgrey").grid(row = 1, column = 4)
Entry(window, width = 10, textvariable = a2).grid(row = 1, column = 5)
Label(window, width = 5, text = "x^2", bg = "lightgrey").grid(row = 1, column = 6)
Entry(window, width = 10, textvariable = a1).grid(row = 1, column = 7)
Label(window, width = 5, text = "x^1", bg = "lightgrey").grid(row = 1, column = 8)
Entry(window, width = 10, textvariable = a0).grid(row = 1, column = 9)
Label(window, width = 5, text = "x^0", bg = "lightgrey").grid(row = 1, column = 10)

Entry(window, width = 10, textvariable = b3).grid(row = 2, column = 3)
Label(window, width = 5, text = "x^3", bg = "lightgrey").grid(row = 2, column = 4)
Entry(window, width = 10, textvariable = b2).grid(row = 2, column = 5)
Label(window, width = 5, text = "x^2", bg = "lightgrey").grid(row = 2, column = 6)
Entry(window, width = 10, textvariable = b1).grid(row = 2, column = 7)
Label(window, width = 5, text = "x^1", bg = "lightgrey").grid(row = 2, column = 8)
Entry(window, width = 10, textvariable = b0).grid(row = 2, column = 9)
Label(window, width = 5, text = "x^0", bg = "lightgrey").grid(row = 2, column = 10)

Button(window, width = 8, text = "馬上計算",bg = "lightgrey", command = calc).grid(row = 3, column = 6)

Label(window, width = 10, textvariable = result6).grid(row = 4, column = 0)
Label(window, width = 5, text = "x^6", bg = "lightgrey").grid(row = 4, column = 1)
Label(window, width = 10, textvariable = result5).grid(row = 4, column = 2)
Label(window, width = 5, text = "x^5", bg = "lightgrey").grid(row = 4, column = 3)
Label(window, width = 10, textvariable = result4).grid(row = 4, column = 4)
Label(window, width = 5, text = "x^4", bg = "lightgrey").grid(row = 4, column = 5)
Label(window, width = 10, textvariable = result3).grid(row = 4, column = 6)
Label(window, width = 5, text = "x^3", bg = "lightgrey").grid(row = 4, column = 7)
Label(window, width = 10, textvariable = result2).grid(row = 4, column = 8)
Label(window, width = 5, text = "x^2", bg = "lightgrey").grid(row = 4, column = 9)
Label(window, width = 10, textvariable = result1).grid(row = 4, column = 10)
Label(window, width = 5, text = "x^1", bg = "lightgrey").grid(row = 4, column = 11)
Label(window, width = 10, textvariable = result0).grid(row = 4, column = 12)
Label(window, width = 5, text = "x^0", bg = "lightgrey").grid(row = 4, column = 13)

window.mainloop()